name: "Agent Research Workflow"
description: "A workflow to run agent-based research tasks."
on:
  workflow_dispatch:
    inputs:
      research_topic_list:
        description: "A comma separated list of research topics for the agent to investigate."
        required: true
        default: '["kubernetes","helm"]'

jobs:
  agent_research:
    runs-on: ubuntu-latest
    # needs: [ prepare ]
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    strategy:
      matrix:
        research_topic: ${{ fromJson(inputs.research_topic_list) }}
    steps:
    - uses: actions/checkout@v5

    - name: "Set up Python"
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      run: |
        uv venv
        uv pip install -r pyproject.toml

    - name: Run Agent Research Script
      run: |
        python agent_researcher.py "${{ matrix.research_topic }}"
