name: "Agent Research Workflow"
description: "A workflow to run agent-based research tasks."
on:
  workflow_dispatch:
    inputs:
      research_topic_list:
        description: "A comma separated list of research topics for the agent to investigate."
        required: true
        default: "Latest advancements in Kubernetes"

jobs:
  agent_research:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    strategy:
      matrix:
        research_topic: ${{ github.event.client_payload.research_topic_list.split(',') }}
    steps:
    - uses: actions/checkout@v5
    - name: "Split "

    - name: "Set up Python"
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      run: |
        uv pip install -r pyproject.toml

    - name: Run Agent Research Script
      run: |
        uv python agent_researcher.py "${{ matrix.research_topic }}"
